api-version: 1.17
author: "James Howarth"
commands: 
  intro: 
    aliases: 
      - introduction
    description: "This is the introduction command."
description: "Use special wands to cast passive spells!"
main: me.Wizardry.Main
name: Wizardry
version: "1.0.4"
